// Generated by CoffeeScript 1.12.7

/*
A collection of methods for retrieving information about the user's system for
bug report purposes.
 */

(function () {
  var jsonPromise;

  module.exports = {
    generateException: function () {
      var e, errMsg;
      try {
        // eslint-disable-next-line no-undef -- intentional ReferenceError for the test
        return a + 1;
      } catch (error) {
        e = error;
        errMsg = e.toString() + " in " + process.env.ATOM_HOME + "/somewhere";
        return window.onerror.call(window, errMsg, "/dev/null", 2, 3, e);
      }
    },
    generateFakeFetchResponses: function (options) {
      if (!window.fetch.isSpy) {
        spyOn(window, "fetch");
      }
      return fetch.andCallFake(function (url) {
        var ref, ref1;
        if (url.indexOf("api.pulsar-edit.dev/api") > -1) {
          return jsonPromise(
            (ref = options != null ? options.packageResponse : void 0) != null
              ? ref
              : {
                  repository: {
                    url: "https://github.com/pulsar-edit/notifications",
                  },
                  releases: {
                    latest: "0.0.0",
                  },
                },
          );
        }
        if ((options != null ? options.issuesErrorResponse : void 0) != null) {
          return Promise.reject(options != null ? options.issuesErrorResponse : void 0);
        }
        return jsonPromise(
          (ref1 = options != null ? options.issuesResponse : void 0) != null
            ? ref1
            : {
                items: [],
              },
        );
      });
    },
  };

  jsonPromise = function (object) {
    return Promise.resolve({
      ok: true,
      json: function () {
        return Promise.resolve(object);
      },
    });
  };
}).call(this);
